services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" # Disable insecure access to the dashboard
      - "--api.dashboard=true" # Enable the dashboard
      - "--providers.docker=true" # Enable Docker provider
      - --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=traefik
      - "--entrypoints.web.address=:80" # HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
    ports:
      - "80:80" # Expose HTTP
      - "443:443" # Expose HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow Traefik to access Docker
      - "./Traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./Traefik/dynconf.yml:/dynconf/dynconf.yml"
      - "../certificates/:/etc/x509/https" # map certificates to container
    networks:
      - traefik
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)" # Dashboard access rule
      - "traefik.http.routers.traefik.entrypoints=https" # Use HTTPS
      - "traefik.http.routers.traefik.tls=true" # Enable TLS
      - "traefik.http.services.traefik.loadbalancer.server.port=8080" # Dashboard port
      #     - "traefik.http.routers.traefik.middlewares=traefik-auth"
      #      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USERFILE_CONTENTS}"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.middlewares=securityHeaders"
      - "traefik.http.middlewares.securityHeaders.headers.customResponseHeaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex"
      - "traefik.http.middlewares.securityHeaders.headers.sslProxyHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.securityHeaders.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.securityHeaders.headers.hostsProxyHeaders=X-Forwarded-Host"
      - "traefik.http.middlewares.securityHeaders.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.securityHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.securityHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.securityHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.securityHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.securityHeaders.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.securityHeaders.headers.stsPreload=true"
  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  traefik:
    driver: bridge
    external: true
    name: traefik
